spring:
  datasource:
    url: jdbc:mysql://localhost:3306/artvis
    username: root
    password: ${DB_MASTER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
jwt:
  secret: ${JWT_SECRET}
---
spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
    web:
      resources:
        add-mappings: false
---
spring:
  servlet:
    multipart:
      max-file-size: 64MB
      location: c:\\Artvis\\Image